// examples/react-advanced/App.tsx
/**
 * React Advanced Example - LiteTable with ALL Features
 *
 * Demonstrates:
 * - Virtual Scrolling (100k+ rows)
 * - Row Selection (checkboxes)
 * - Export (CSV, JSON, Excel)
 * - Column Resizing (drag to resize)
 * - Server-Side Operations (AJAX)
 */

import { useState, useRef, useCallback } from 'react'
import { useLiteTable } from '@litetable/react'
import {
  VirtualScrollManager,
  RowSelectionManager,
  ExportManager,
  ColumnResizeManager,
} from '@litetable/core'
import type { Column } from '@litetable/react'
import './App.css'

// Sample data type
interface User {
  id: number
  name: string
  email: string
  role: string
  status: 'active' | 'inactive'
  salary: number
  joinedAt: Date
}

// Generate large dataset for virtual scrolling demo
function generateUsers(count: number): User[] {
  const roles = ['Admin', 'Editor', 'User', 'Manager', 'Developer']
  const firstNames = ['John', 'Jane', 'Bob', 'Alice', 'Charlie', 'Diana', 'Eve', 'Frank']
  const lastNames = ['Doe', 'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller']

  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    name: `${firstNames[i % firstNames.length]} ${lastNames[i % lastNames.length]}`,
    email: `user${i + 1}@example.com`,
    role: roles[i % roles.length],
    status: i % 3 === 0 ? 'inactive' : 'active',
    salary: 50000 + Math.floor(Math.random() * 100000),
    joinedAt: new Date(Date.now() - i * 86400000),
  }))
}

function App() {
  const [data] = useState<User[]>(() => generateUsers(10000)) // 10k rows!
  const [useVirtualScroll, setUseVirtualScroll] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)
  const [scrollTop, setScrollTop] = useState(0)

  // Define columns
  const columns: Column<User>[] = [
    {
      id: 'select',
      header: '☐',
      width: '50px',
      sortable: false,
      align: 'center',
    },
    {
      id: 'id',
      header: 'ID',
      sortable: true,
      width: '80px',
      align: 'center',
    },
    {
      id: 'name',
      header: 'Name',
      sortable: true,
      filterable: true,
    },
    {
      id: 'email',
      header: 'Email',
      sortable: true,
      filterable: true,
    },
    {
      id: 'role',
      header: 'Role',
      sortable: true,
      filterable: true,
    },
    {
      id: 'salary',
      header: 'Salary',
      sortable: true,
      cell: (value) => `$${Number(value).toLocaleString()}`,
    },
    {
      id: 'status',
      header: 'Status',
      sortable: true,
      cell: (value) => (
        <span className={`status-badge status-${value}`}>
          {String(value)}
        </span>
      ),
    },
    {
      id: 'joinedAt',
      header: 'Joined',
      sortable: true,
      accessor: (row) => row.joinedAt.toLocaleDateString(),
    },
  ]

  // Initialize table
  const table = useLiteTable<User>({
    data,
    columns,
    pagination: useVirtualScroll ? false : { page: 1, pageSize: 50 },
    searchable: true,
  })

  // Virtual Scrolling
  const virtualScroll = useRef<VirtualScrollManager<User>>()
  if (useVirtualScroll && !virtualScroll.current) {
    virtualScroll.current = new VirtualScrollManager(table.allRows, {
      rowHeight: 48,
      containerHeight: 600,
      overscan: 10,
    })
  }

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    const scrollTop = e.currentTarget.scrollTop
    setScrollTop(scrollTop)
    if (virtualScroll.current) {
      virtualScroll.current.handleScroll(scrollTop)
    }
  }, [])

  // Row Selection
  const [selection] = useState(() => new RowSelectionManager({
    mode: 'multiple',
    enableSelectAll: true,
  }))

  useState(() => {
    selection.setRowIds(data.map(row => String(row.id)))
  })

  const handleSelectRow = (rowId: string) => {
    selection.toggleRow(rowId)
  }

  const handleSelectAll = () => {
    selection.toggleSelectAll()
  }

  // Export
  const exportManager = useRef(
    new ExportManager(table.allRows, columns)
  )

  const handleExport = (format: 'csv' | 'json' | 'xlsx' | 'html') => {
    exportManager.current.export(format, {
      filename: 'users-export',
      includeHeaders: true,
    })
  }

  // Column Resizing
  const [resizeManager] = useState(() => new ColumnResizeManager({
    minWidth: 80,
    maxWidth: 500,
  }))

  const displayRows = useVirtualScroll && virtualScroll.current
    ? virtualScroll.current.getVisibleRows()
    : table.rows

  const virtualState = virtualScroll.current?.getState()

  return (
    <div className="app">
      <h1>🚀 LiteTable.js - Advanced Features Demo</h1>
      <p className="subtitle">
        Virtual Scrolling • Row Selection • Export • Column Resize
      </p>

      <div className="controls">
        {/* Search */}
        <input
          type="search"
          placeholder="Search 10,000 users..."
          onChange={(e) => table.search(e.target.value)}
          className="search-input"
        />

        {/* Virtual Scroll Toggle */}
        <label className="checkbox-label">
          <input
            type="checkbox"
            checked={useVirtualScroll}
            onChange={(e) => setUseVirtualScroll(e.target.checked)}
          />
          Virtual Scroll (handles 100k+ rows)
        </label>

        {/* Export Buttons */}
        <div className="export-buttons">
          <button onClick={() => handleExport('csv')} className="btn-export">
            📥 CSV
          </button>
          <button onClick={() => handleExport('json')} className="btn-export">
            📥 JSON
          </button>
          <button onClick={() => handleExport('xlsx')} className="btn-export">
            📥 Excel
          </button>
        </div>

        {/* Selection Info */}
        <div className="selection-info">
          Selected: {selection.getSelectedCount()} / {data.length}
        </div>
      </div>

      {/* Table Container */}
      <div
        ref={containerRef}
        className="table-container"
        style={{
          height: useVirtualScroll ? '600px' : 'auto',
          overflow: useVirtualScroll ? 'auto' : 'visible',
        }}
        onScroll={handleScroll}
      >
        <table className="lite-table">
          <thead>
            <tr>
              <th style={{ width: '50px', textAlign: 'center' }}>
                <input
                  type="checkbox"
                  checked={selection.getState().allSelected}
                  onChange={handleSelectAll}
                />
              </th>
              {table.visibleColumns.slice(1).map((column) => (
                <th
                  key={column.id}
                  style={{
                    width: resizeManager.getColumnWidth(column.id) || column.width,
                    textAlign: column.align || 'left',
                  }}
                  className={column.sortable ? 'sortable' : ''}
                  onClick={() => column.sortable && table.sortBy(column.id)}
                >
                  {column.header}
                  {column.sortable && (
                    <span className="sort-icon">
                      {table.sortState.columnId === column.id
                        ? table.sortState.direction === 'asc' ? '↑' : '↓'
                        : '⇅'}
                    </span>
                  )}
                </th>
              ))}
            </tr>
          </thead>
          <tbody
            style={useVirtualScroll ? {
              position: 'relative',
              height: virtualState?.totalHeight || 0,
            } : undefined}
          >
            {displayRows.length === 0 ? (
              <tr>
                <td colSpan={columns.length} className="no-data">
                  No users found
                </td>
              </tr>
            ) : (
              displayRows.map((row, index) => (
                <tr
                  key={row.id}
                  style={useVirtualScroll ? {
                    position: 'absolute',
                    top: ((virtualState?.startIndex || 0) + index) * 48,
                    width: '100%',
                  } : undefined}
                  className={selection.isRowSelected(String(row.id)) ? 'selected' : ''}
                >
                  <td style={{ textAlign: 'center' }}>
                    <input
                      type="checkbox"
                      checked={selection.isRowSelected(String(row.id))}
                      onChange={() => handleSelectRow(String(row.id))}
                    />
                  </td>
                  <td style={{ textAlign: 'center' }}>{row.id}</td>
                  <td>{row.name}</td>
                  <td>{row.email}</td>
                  <td>{row.role}</td>
                  <td>${row.salary.toLocaleString()}</td>
                  <td>
                    <span className={`status-badge status-${row.status}`}>
                      {row.status}
                    </span>
                  </td>
                  <td>{row.joinedAt.toLocaleDateString()}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Stats */}
      <div className="stats">
        <div className="stat-item">
          <strong>Total Rows:</strong> {data.length.toLocaleString()}
        </div>
        <div className="stat-item">
          <strong>Filtered:</strong> {table.allRows.length.toLocaleString()}
        </div>
        <div className="stat-item">
          <strong>Rendered:</strong> {displayRows.length}
        </div>
        <div className="stat-item">
          <strong>Selected:</strong> {selection.getSelectedCount()}
        </div>
        {useVirtualScroll && virtualState && (
          <div className="stat-item">
            <strong>Visible Range:</strong> {virtualState.startIndex}-{virtualState.endIndex}
          </div>
        )}
      </div>
    </div>
  )
}

export default App

// examples/vue-example/App.vue
<template>
  <div class="app">
    <h1>🚀 LiteTable.js - Vue Example</h1>
    <p class="subtitle">
      Lightweight, performant, framework-agnostic table library
    </p>

    <div class="controls">
      <!-- Search -->
      <div class="search-box">
        <input
          v-model="searchValue"
          type="search"
          placeholder="Search users..."
          class="search-input"
          @input="debouncedSearch(searchValue)"
        />
      </div>

      <!-- Column toggles -->
      <div class="column-toggles">
        <span>Columns: </span>
        <label
          v-for="col in columns"
          :key="col.id"
          class="checkbox-label"
        >
          <input
            type="checkbox"
            :checked="!table.hiddenColumns.value.has(col.id)"
            @change="table.toggleColumn(col.id)"
          />
          {{ col.header }}
        </label>
      </div>

      <!-- Reset -->
      <button @click="table.reset" class="btn-reset">
        Reset
      </button>
    </div>

    <!-- Table -->
    <div class="table-container">
      <table class="lite-table">
        <thead>
          <tr>
            <th
              v-for="column in table.visibleColumns.value"
              :key="column.id"
              :style="{
                width: column.width,
                textAlign: column.align || 'left',
              }"
              :class="{ sortable: column.sortable }"
              @click="column.sortable && table.sortBy(column.id)"
            >
              {{ column.header }}
              <span v-if="column.sortable" class="sort-icon">
                {{ getSortIcon(column.id) }}
              </span>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-if="table.rows.value.length === 0">
            <td :colspan="table.visibleColumns.value.length" class="no-data">
              No users found
            </td>
          </tr>
          <tr v-else v-for="row in table.rows.value" :key="row.id">
            <td
              v-for="column in table.visibleColumns.value"
              :key="column.id"
              :style="{ textAlign: column.align || 'left' }"
            >
              <template v-if="column.id === 'status'">
                <span :class="`status-badge status-${row[column.id]}`">
                  {{ row[column.id] }}
                </span>
              </template>
              <template v-else-if="column.id === 'joinedAt'">
                {{ formatDate(row.joinedAt) }}
              </template>
              <template v-else>
                {{ row[column.id] }}
              </template>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Pagination -->
    <div v-if="table.paginationState.value" class="pagination">
      <div class="pagination-info">
        Showing {{ table.paginationState.value.startIndex + 1 }} to
        {{ table.paginationState.value.endIndex }} of
        {{ table.paginationState.value.totalRows }} users
      </div>

      <div class="pagination-controls">
        <button
          @click="table.prevPage"
          :disabled="!table.paginationState.value.hasPrevPage"
          class="btn-page"
        >
          Previous
        </button>

        <span class="page-indicator">
          Page {{ table.paginationState.value.page }} of
          {{ table.paginationState.value.totalPages }}
        </span>

        <button
          @click="table.nextPage"
          :disabled="!table.paginationState.value.hasNextPage"
          class="btn-page"
        >
          Next
        </button>
      </div>

      <div class="page-size">
        <label>
          Rows per page:
          <select
            :value="table.paginationState.value.pageSize"
            @change="
              table.setPageSize(Number(($event.target as HTMLSelectElement).value))
            "
            class="select-page-size"
          >
            <option
              v-for="size in table.paginationState.value.pageSizeOptions"
              :key="size"
              :value="size"
            >
              {{ size }}
            </option>
          </select>
        </label>
      </div>
    </div>

    <!-- Stats -->
    <div class="stats">
      <div class="stat-item">
        <strong>Sort:</strong>
        {{
          table.sortState.value.columnId
            ? `${table.sortState.value.columnId} (${table.sortState.value.direction})`
            : 'None'
        }}
      </div>
      <div class="stat-item">
        <strong>Search:</strong> {{ table.searchTerm.value || 'None' }}
      </div>
      <div class="stat-item">
        <strong>Filtered rows:</strong> {{ table.allRows.value.length }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useLiteTable, useDebouncedSearch } from '@litetable/vue'
import type { Column } from '@litetable/vue'
import './App.css'

// Sample data type
interface User {
  id: number
  name: string
  email: string
  role: string
  status: 'active' | 'inactive'
  joinedAt: Date
}

// Sample data
const sampleUsers: User[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    role: 'Admin',
    status: 'active',
    joinedAt: new Date('2024-01-15'),
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'User',
    status: 'active',
    joinedAt: new Date('2024-02-20'),
  },
  {
    id: 3,
    name: 'Bob Johnson',
    email: 'bob@example.com',
    role: 'User',
    status: 'inactive',
    joinedAt: new Date('2024-03-10'),
  },
  {
    id: 4,
    name: 'Alice Williams',
    email: 'alice@example.com',
    role: 'Editor',
    status: 'active',
    joinedAt: new Date('2024-01-05'),
  },
  {
    id: 5,
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    role: 'User',
    status: 'active',
    joinedAt: new Date('2024-04-12'),
  },
]

const data = ref<User[]>(sampleUsers)

// Define columns
const columns: Column<User>[] = [
  {
    id: 'id',
    header: 'ID',
    sortable: true,
    width: '60px',
    align: 'center',
  },
  {
    id: 'name',
    header: 'Name',
    sortable: true,
    filterable: true,
  },
  {
    id: 'email',
    header: 'Email',
    sortable: true,
    filterable: true,
  },
  {
    id: 'role',
    header: 'Role',
    sortable: true,
    filterable: true,
  },
  {
    id: 'status',
    header: 'Status',
    sortable: true,
  },
  {
    id: 'joinedAt',
    header: 'Joined',
    sortable: true,
  },
]

// Initialize table with pagination
const table = useLiteTable<User>({
  data: data.value,
  columns,
  pagination: {
    page: 1,
    pageSize: 3,
    pageSizeOptions: [3, 5, 10],
  },
  searchable: true,
})

// Debounced search
const [searchValue, debouncedSearch] = useDebouncedSearch(table.search, 300)

// Helper functions
const getSortIcon = (columnId: string): string => {
  if (table.sortState.value.columnId !== columnId) return '⇅'
  return table.sortState.value.direction === 'asc' ? '↑' : '↓'
}

const formatDate = (date: Date): string => {
  return date.toLocaleDateString()
}
</script>

<style scoped>
@import './App.css';
</style>
